feat: clin-2959 -  SASS migration to vanilla CSS
Ferlab-Ste-Justine/clin-portal-theme pull request #27
Opened 2024-06-26 21:04 UTC by emmanuelnau

# FEAT: CLIN-2959 Migrate SCSS to CSS for ferlab-ui 10

https://ferlab-crsj.atlassian.net/browse/CLIN-2959

2024-06-27 13:32 UTC, francisl requested changes

2024-06-27 13:32 UTC, francisl commented on themes/clin/colors.css
>    blueBase: #00aceb;
je sais pas si le :export est utilisé

les @import c'est du sass, il faut les enlever

2024-06-27 14:22 UTC, emmanuelnau commented on themes/clin/colors.css
>    blueBase: #00aceb;
Ok j'enlève le :export
Le @import c'est du CSS aussi. C'est supporté depuis longtemps on devrait pas avoir de problème non ?
Moi ca marche bien en tous cas en local. Et le build semble le supporter aussi et générer les bons fichiers

2024-07-05 14:01 UTC, francisl approved these changes
🍻

2024-07-05 14:02 UTC, merged